# https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

[tool.black]
line-length = 127
target-version = ['py311']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "test"
]